/**
 * Barrel file exporting ALL source plugin modules.
 *
 * Import this in JobsModule to register all 160+ source plugins:
 *   import { ALL_SOURCE_MODULES } from '@ever-jobs/plugin-sources';
 *   @Module({ imports: [PluginModule, ...ALL_SOURCE_MODULES] })
 *
 * @auto-generated by scripts/gen-barrel.ps1
 */
import { FourDayWeekModule } from './source-4dayweek';
import { AcademiccareersModule } from './source-academiccareers';
import { AdzunaModule } from './source-adzuna';
import { AndroidjobsModule } from './source-androidjobs';
import { ArbeitnowModule } from './source-arbeitnow';
import { ArbeitsagenturModule } from './source-arbeitsagentur';
import { AdpModule } from './source-ats-adp';
import { AshbyModule } from './source-ats-ashby';
import { BambooHRModule } from './source-ats-bamboohr';
import { BreezyHRModule } from './source-ats-breezyhr';
import { BullhornModule } from './source-ats-bullhorn';
import { ComeetModule } from './source-ats-comeet';
import { CrelateModule } from './source-ats-crelate';
import { DeelModule } from './source-ats-deel';
import { FountainModule } from './source-ats-fountain';
import { FreshteamModule } from './source-ats-freshteam';
import { GreenhouseModule } from './source-ats-greenhouse';
import { HiringThingModule } from './source-ats-hiringthing';
import { HomerunModule } from './source-ats-homerun';
import { IcimsModule } from './source-ats-icims';
import { ISmartRecruitModule } from './source-ats-ismartrecruit';
import { JazzHRModule } from './source-ats-jazzhr';
import { JobScoreModule } from './source-ats-jobscore';
import { JobviteModule } from './source-ats-jobvite';
import { JobylonModule } from './source-ats-jobylon';
import { LeverModule } from './source-ats-lever';
import { LoxoModule } from './source-ats-loxo';
import { ManatalModule } from './source-ats-manatal';
import { PaylocityModule } from './source-ats-paylocity';
import { PersonioModule } from './source-ats-personio';
import { PhenomModule } from './source-ats-phenom';
import { PinpointModule } from './source-ats-pinpoint';
import { RecruiteeModule } from './source-ats-recruitee';
import { RecruiterflowModule } from './source-ats-recruiterflow';
import { RipplingModule } from './source-ats-rippling';
import { SmartRecruitersModule } from './source-ats-smartrecruiters';
import { SuccessFactorsModule } from './source-ats-successfactors';
import { TalentLyftModule } from './source-ats-talentlyft';
import { TaleoModule } from './source-ats-taleo';
import { TeamtailorModule } from './source-ats-teamtailor';
import { TrakstarModule } from './source-ats-trakstar';
import { UkgModule } from './source-ats-ukg';
import { WorkableModule } from './source-ats-workable';
import { WorkdayModule } from './source-ats-workday';
import { AuthenticJobsModule } from './source-authenticjobs';
import { BaytModule } from './source-bayt';
import { BDJobsModule } from './source-bdjobs';
import { BerlinStartupJobsModule } from './source-berlinstartupjobs';
import { BuiltInModule } from './source-builtin';
import { CanadaJobBankModule } from './source-canadajobbank';
import { CareerBuilderModule } from './source-careerbuilder';
import { CareerJetModule } from './source-careerjet';
import { CareerOneStopModule } from './source-careeronestop';
import { ClojurejobsModule } from './source-clojurejobs';
import { AmazonModule } from './source-company-amazon';
import { AppleModule } from './source-company-apple';
import { BoeingModule } from './source-company-boeing';
import { CursorModule } from './source-company-cursor';
import { GoogleCareersModule } from './source-company-google';
import { IbmModule } from './source-company-ibm';
import { MetaModule } from './source-company-meta';
import { MicrosoftModule } from './source-company-microsoft';
import { NetflixModule } from './source-company-netflix';
import { NvidiaModule } from './source-company-nvidia';
import { OpenAIModule } from './source-company-openai';
import { StripeModule } from './source-company-stripe';
import { TikTokModule } from './source-company-tiktok';
import { UberModule } from './source-company-uber';
import { ZoomModule } from './source-company-zoom';
import { ConservationJobsModule } from './source-conservationjobs';
import { CoroflotModule } from './source-coroflot';
import { CrunchboardModule } from './source-crunchboard';
import { CryptocurrencyJobsModule } from './source-cryptocurrencyjobs';
import { CryptoJobsListModule } from './source-cryptojobslist';
import { DevITJobsModule } from './source-devitjobs';
import { DevopsjobsModule } from './source-devopsjobs';
import { DiceModule } from './source-dice';
import { DjinniModule } from './source-djinni';
import { DribbbleModule } from './source-dribbble';
import { DrupalJobsModule } from './source-drupaljobs';
import { DuunitoriModule } from './source-duunitori';
import { EchoJobsModule } from './source-echojobs';
import { EcojobsModule } from './source-ecojobs';
import { ElixirJobsModule } from './source-elixirjobs';
import { EurojobsModule } from './source-eurojobs';
import { ExaModule } from './source-exa';
import { FindWorkModule } from './source-findwork';
import { FossJobsModule } from './source-fossjobs';
import { FranceTravailModule } from './source-francetravail';
import { FreelancerComModule } from './source-freelancercom';
import { FunctionalworksModule } from './source-functionalworks';
import { GermantechjobsModule } from './source-germantechjobs';
import { GetOnBoardModule } from './source-getonboard';
import { GlassdoorModule } from './source-glassdoor';
import { GolangJobsModule } from './source-golangjobs';
import { GoogleModule } from './source-google';
import { GreenJobsBoardModule } from './source-greenjobsboard';
import { GuardianjobsModule } from './source-guardianjobs';
import { HabrcareerModule } from './source-habrcareer';
import { HackerNewsModule } from './source-hackernews';
import { HasJobModule } from './source-hasjob';
import { HeadhunterModule } from './source-headhunter';
import { HigherEdJobsModule } from './source-higheredjobs';
import { HimalayasModule } from './source-himalayas';
import { IcrunchdataModule } from './source-icrunchdata';
import { IndeedModule } from './source-indeed';
import { InfoJobsModule } from './source-infojobs';
import { IosdevjobsModule } from './source-iosdevjobs';
import { JobDataApiModule } from './source-jobdataapi';
import { JobicyModule } from './source-jobicy';
import { JobindexModule } from './source-jobindex';
import { JobsAcUkModule } from './source-jobsacuk';
import { JobsChModule } from './source-jobsch';
import { JobsdbModule } from './source-jobsdb';
import { JobsInJapanModule } from './source-jobsinjapan';
import { JobspressoModule } from './source-jobspresso';
import { JobstreetModule } from './source-jobstreet';
import { JobTechDevModule } from './source-jobtechdev';
import { JoinRiseModule } from './source-joinrise';
import { JoobleModule } from './source-jooble';
import { LandingJobsModule } from './source-landingjobs';
import { LaraJobsModule } from './source-larajobs';
import { LinkedInModule } from './source-linkedin';
import { MonsterModule } from './source-monster';
import { MycareersfutureModule } from './source-mycareersfuture';
import { NaukriModule } from './source-naukri';
import { NavJobsModule } from './source-navjobs';
import { NoDeskModule } from './source-nodesk';
import { NoFluffJobsModule } from './source-nofluffjobs';
import { OpensourcedesignjobsModule } from './source-opensourcedesignjobs';
import { PowertoflyModule } from './source-powertofly';
import { PyJobsModule } from './source-pyjobs';
import { PythonJobsModule } from './source-pythonjobs';
import { RailsJobsModule } from './source-railsjobs';
import { RealWorkFromAnywhereModule } from './source-realworkfromanywhere';
import { ReedModule } from './source-reed';
import { ReliefWebModule } from './source-reliefweb';
import { RemotefirstjobsModule } from './source-remotefirstjobs';
import { RemoteOkModule } from './source-remoteok';
import { RemotiveModule } from './source-remotive';
import { SimplyHiredModule } from './source-simplyhired';
import { SnagajobModule } from './source-snagajob';
import { StartupJobsModule } from './source-startupjobs';
import { StepStoneModule } from './source-stepstone';
import { SwissdevjobsModule } from './source-swissdevjobs';
import { TalrooModule } from './source-talroo';
import { TechcareersModule } from './source-techcareers';
import { TheMuseModule } from './source-themuse';
import { UndpJobsModule } from './source-undpjobs';
import { UpworkModule } from './source-upwork';
import { UsajobsModule } from './source-usajobs';
import { VirtualVocationsModule } from './source-virtualvocations';
import { VueJobsModule } from './source-vuejobs';
import { Web3CareerModule } from './source-web3career';
import { WellfoundModule } from './source-wellfound';
import { WeWorkRemotelyModule } from './source-weworkremotely';
import { WordPressJobsModule } from './source-wordpressjobs';
import { WorkingNomadsModule } from './source-workingnomads';
import { ZipRecruiterModule } from './source-ziprecruiter';

export const ALL_SOURCE_MODULES = [
  FourDayWeekModule,
  AcademiccareersModule,
  AdzunaModule,
  AndroidjobsModule,
  ArbeitnowModule,
  ArbeitsagenturModule,
  AdpModule,
  AshbyModule,
  BambooHRModule,
  BreezyHRModule,
  BullhornModule,
  ComeetModule,
  CrelateModule,
  DeelModule,
  FountainModule,
  FreshteamModule,
  GreenhouseModule,
  HiringThingModule,
  HomerunModule,
  IcimsModule,
  ISmartRecruitModule,
  JazzHRModule,
  JobScoreModule,
  JobviteModule,
  JobylonModule,
  LeverModule,
  LoxoModule,
  ManatalModule,
  PaylocityModule,
  PersonioModule,
  PhenomModule,
  PinpointModule,
  RecruiteeModule,
  RecruiterflowModule,
  RipplingModule,
  SmartRecruitersModule,
  SuccessFactorsModule,
  TalentLyftModule,
  TaleoModule,
  TeamtailorModule,
  TrakstarModule,
  UkgModule,
  WorkableModule,
  WorkdayModule,
  AuthenticJobsModule,
  BaytModule,
  BDJobsModule,
  BerlinStartupJobsModule,
  BuiltInModule,
  CanadaJobBankModule,
  CareerBuilderModule,
  CareerJetModule,
  CareerOneStopModule,
  ClojurejobsModule,
  AmazonModule,
  AppleModule,
  BoeingModule,
  CursorModule,
  GoogleCareersModule,
  IbmModule,
  MetaModule,
  MicrosoftModule,
  NetflixModule,
  NvidiaModule,
  OpenAIModule,
  StripeModule,
  TikTokModule,
  UberModule,
  ZoomModule,
  ConservationJobsModule,
  CoroflotModule,
  CrunchboardModule,
  CryptocurrencyJobsModule,
  CryptoJobsListModule,
  DevITJobsModule,
  DevopsjobsModule,
  DiceModule,
  DjinniModule,
  DribbbleModule,
  DrupalJobsModule,
  DuunitoriModule,
  EchoJobsModule,
  EcojobsModule,
  ElixirJobsModule,
  EurojobsModule,
  ExaModule,
  FindWorkModule,
  FossJobsModule,
  FranceTravailModule,
  FreelancerComModule,
  FunctionalworksModule,
  GermantechjobsModule,
  GetOnBoardModule,
  GlassdoorModule,
  GolangJobsModule,
  GoogleModule,
  GreenJobsBoardModule,
  GuardianjobsModule,
  HabrcareerModule,
  HackerNewsModule,
  HasJobModule,
  HeadhunterModule,
  HigherEdJobsModule,
  HimalayasModule,
  IcrunchdataModule,
  IndeedModule,
  InfoJobsModule,
  IosdevjobsModule,
  JobDataApiModule,
  JobicyModule,
  JobindexModule,
  JobsAcUkModule,
  JobsChModule,
  JobsdbModule,
  JobsInJapanModule,
  JobspressoModule,
  JobstreetModule,
  JobTechDevModule,
  JoinRiseModule,
  JoobleModule,
  LandingJobsModule,
  LaraJobsModule,
  LinkedInModule,
  MonsterModule,
  MycareersfutureModule,
  NaukriModule,
  NavJobsModule,
  NoDeskModule,
  NoFluffJobsModule,
  OpensourcedesignjobsModule,
  PowertoflyModule,
  PyJobsModule,
  PythonJobsModule,
  RailsJobsModule,
  RealWorkFromAnywhereModule,
  ReedModule,
  ReliefWebModule,
  RemotefirstjobsModule,
  RemoteOkModule,
  RemotiveModule,
  SimplyHiredModule,
  SnagajobModule,
  StartupJobsModule,
  StepStoneModule,
  SwissdevjobsModule,
  TalrooModule,
  TechcareersModule,
  TheMuseModule,
  UndpJobsModule,
  UpworkModule,
  UsajobsModule,
  VirtualVocationsModule,
  VueJobsModule,
  Web3CareerModule,
  WellfoundModule,
  WeWorkRemotelyModule,
  WordPressJobsModule,
  WorkingNomadsModule,
  ZipRecruiterModule,
];